### ISSUE TITLE
Secrets Scan not working

### ISSUE THREAD

**Issue by mukul-seagate11** [edplato/trufflehog-actions-scan#11]
GitHub Actions is unable to scan & fetch secrets [as secret exist] from code as integrated in repo,

https://github.com/mukul-seagate11/cortx-hare/pull/1/checks?check_run_id=2361518131

Is anything missing?

**Comment by mukul-seagate11** [comment]
@edplato, I dont see this issue is assigned to anyone?

**Comment by edplato** [comment]
Hello, you will need to add that custom `token` and a matching regex for the key to your custom regex rules `regexes.json` file. I was able to locally catch the token with this strategy using `trufflehog`.
