### ISSUE TITLE
Updating README to account for github actions/checkout@v2 

### ISSUE THREAD

**Issue by armaanshah96** [edplato/trufflehog-actions-scan#16]
Thanks for making this github action. This issue is not directly related to this action, but may be relevant for users.

I noticed that  the max_depth flag wasn't working when I was attempting to use it and after some investigation I realized that `- uses: actions/checkout@v2` only takes the last commit by default.

Per the README on https://github.com/actions/checkout (emphasis mine):
> **Only a single commit is fetched by default**, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags.

Unless I've misunderstood something, it may be worthwhile to update the README adding
```
with:
    fetch-depth: 0
```
is required to make available the entire git commit history. I also recognize that this action is built to be running on a 'clean' repo though, so latest commit should be sufficient (unless multiple commit PRs need to be supported).

I'm not sure if this is the best solution because specifying the fetch depth for actions checkout and then the max_depth on the trufflehog level seem to overlap or can be redundant.

**Comment by armaanshah96** [comment]
Actually it seems that `actions/checkout@master` would have the same issue (https://github.com/actions/checkout/tree/master), but will hold off on updating the README again for now. I'm new to Github Actions so I may be missing something

**Comment by armaanshah96** [comment]
Actually it seems that `actions/checkout@master` would have the same issue based on its README, but will hold off on updating the README again for now. I'm new to Github Actions so I may be missing something

**Comment by sammcj** [comment]
I think you're correct @armaanshah96 , it seems pretty broken with checkout v2 / master.

It seems @edplato may be AFK though, perhaps this repo should be forked and maintained by multiple people?

**Comment by edplato** [comment]
Sorry to leave you hanging there @armaanshah96 - great fix and documentation on your change.

Thanks for the poke @sammcj.
