### ISSUE TITLE
Scan the repo but not all historical commit

### ISSUE THREAD

**Issue by sjgupta19** [edplato/trufflehog-actions-scan#19]
I want to scan the repo. I am using max-depth flag as well, but that will check the files changed in the current commit. Even If i remove the secret it is still exiting in error as it is detecting secrets.

**Comment by edplato** [comment]
Hi, could you share your actions workflow config so I can see your settings?

**Comment by edplato** [comment]
I'm going to close this out for now, but please feel free to reopen/update with your workflow config to assist in debugging if you're still experiencing issues.
