### ISSUE TITLE
Image fails because of invalid requirements

### ISSUE THREAD

**Issue by fmigneault** [edplato/trufflehog-actions-scan#5]
https://github.com/gitpython-developers/GitPython/issues/984

rebuilt from not pinned version now causes failing action:
https://github.com/crim-ca/weaver/pull/80/checks?check_run_id=451203427

**Comment by edplato** [comment]
Thanks, this seems to be an issue with a `trufflehog` dependency update (https://github.com/dxa4481/truffleHog/issues/200). I just made the recommended version fix in that issue and it appears to be working.

**Comment by fmigneault** [comment]
Thanks!
