### ISSUE TITLE
Scan Arguments not finding issues it should be finding

### ISSUE THREAD

**Issue by shehackspurple** [edplato/trufflehog-actions-scan#8]
Hi Ed, sorry to bother you again, but since you have checked in your changes, it can't find my keys again. It finds nothing.

I ran trufflehog from my desktop on my repo and it found lots of stuff, with no special arguments: trufflehog https://github.com/shehackspurple/dotnetcore-webapp

I made a video of the whole thing, so you can see my troubleshooting: 
https://www.twitch.tv/videos/565679444

I'm confused as to why it worked when it was in a branch, you merged it to master, then it's not working again. Did anything else change besides that and the update to the readme?

**Comment by edplato** [comment]
Hi, no worries. Let me know if this helps out. The main difference I'm seeing in running `trufflehog` in the command line vs. running this Action is there are default arguments being used with this Action that aren't included by default in the command line.

If you run `trufflehog --regex --entropy=False --max_depth=50` in the command line you should see similar scan results to the default arguments used for this Action. The additional `--rules /regexes.json` should work locally on the command line too, but you may have to play around with changing the relative paths.

I just added a new option to the `master` branch so if you do:
```
with:
    scanArguments: " "
```
then it will only run `trufflehog` without any arguments. That should replicate what you are seeing when you run on the command line. Although when the `entropy` option is `true` then you may end up getting some results that have a lot of false positives.

**Comment by shehackspurple** [comment]
Thanks for all your help, it works now.

**Comment by shehackspurple** [comment]
Closing now.
